### ISSUE TITLE
Library version?

### ISSUE THREAD

**Issue by exoRift** [nathsou/EEPROM-Burner#1]
Do you happen to have/know a library version of this I can utilize in a script rather than as a CLI?

**Comment by nathsou** [comment]
Have you found a solution? I could make the underlying functions public for other packages.

**Comment by exoRift** [comment]
So, I did not find a solution, however, I couldn't use this project anyway because it requires a middleman flashed onto the board. I was hoping I could directly communicate with the EEPROM via USB.

**Comment by nathsou** [comment]
I see, I'm closing the issue then. Good luck with your project!
